#!/usr/bin/env python3
"""Produces a single-header libzarr (zarr.hpp) by inlining the libzarr/
includes of the umbrella header in dependency order. System includes are
deduplicated and hoisted; feature guards (LIBZARR_HAS_*) are preserved.
The vendored nlohmann/json include is left as-is: ship third_party/ next to
the amalgamated header (or use LIBZARR_EXTERNAL_JSON's include path).

Usage: tools/amalgamate.py [output]   (default: build/zarr.hpp)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INCLUDE = ROOT / "include"

LOCAL_INCLUDE = re.compile(r'^#include "(libzarr/[^"]+)"')
GUARD = re.compile(r"^#(?:ifndef|define) LIBZARR_[A-Z_]+_HPP$|^#endif  // LIBZARR_[A-Z_]+_HPP$")


def inline(path: Path, seen: set, out: list) -> None:
    if path in seen:
        return
    seen.add(path)
    for line in path.read_text().splitlines():
        match = LOCAL_INCLUDE.match(line)
        if match:
            inline(INCLUDE / match.group(1), seen, out)
        elif GUARD.match(line):
            continue  # per-file guards are redundant inside the amalgamation
        else:
            out.append(line)


def main() -> None:
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "build" / "zarr.hpp"
    body: list = []
    inline(INCLUDE / "libzarr" / "libzarr.hpp", set(), body)

    lines = ["// libzarr amalgamated header — generated by tools/amalgamate.py; do not edit.",
             "#ifndef LIBZARR_AMALGAMATED_HPP", "#define LIBZARR_AMALGAMATED_HPP"]
    emitted_system = set()
    for line in body:
        if line.startswith("#include <") and "nlohmann" not in line and "zlib" not in line \
                and "blosc" not in line:
            if line in emitted_system:
                continue
            emitted_system.add(line)
        lines.append(line)
    lines += ["#endif  // LIBZARR_AMALGAMATED_HPP", ""]

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines))
    print(f"wrote {target} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
